### ISSUE TITLE
Error when fetching module

### ISSUE THREAD

**Issue by jd1378** [velo-org/velo#4]
When trying to import LFU from mod.ts, I get 3 more errors similar to this:
```
Check https://deno.land/x/velo@0.1.4/mod.ts
error: TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { Key } from "./src/models/key.ts";
~~~
```
also there is a warning which I don't mind much: 
```
Warning Implicitly using latest version (0.84.0) for https://deno.land/std/node/events.ts
```

 - OS: Windows 10 20H2
 - Deno 1.7.0

**Additional context**
all 4 error:
```
error: TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { Key } from "./src/models/key.ts";
         ~~~
    at https://deno.land/x/velo@0.1.4/mod.ts:7:10

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { Options } from "./src/models/options.ts";
         ~~~~~~~
    at https://deno.land/x/velo@0.1.4/mod.ts:8:10

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { SLRUOptions } from "./src/models/slruOptions.ts";
         ~~~~~~~~~~~
    at https://deno.land/x/velo@0.1.4/mod.ts:9:10

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { CacheStatistics } from "./src/models/cacheStatistics.ts";
         ~~~~~~~~~~~~~~~
    at https://deno.land/x/velo@0.1.4/mod.ts:10:10

Found 4 errors.
```

**Comment by KaindlJulian** [comment]
@jd1378 thanks for letting us know, this should be fixed now
